language: android
sudo: required
jdk: oraclejdk8
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-30
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "platforms;android-30"


before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build
